Metrics/LineLength:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MethodLength:
  Enabled: false